[package]
name = "actix-server"
version = "0.1.0"
authors = ["gsuyemoto <gsuyemoto@gmail.com>"]
edition = "2018"

[dependencies]
actix-http = "2"
actix-web = "3"
handlebars = { version = "3.0.0", features = ["dir_source"] }
serde_json = "1.0"
pnet = "0.28.0"
pnet_datalink = "0.28.0"
