[package]
name = "actix-server"
version = "0.1.0"
authors = ["gsuyemoto <gsuyemoto@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
actix-http = "2"
actix-web = "3"
handlebars = { version = "3.0.0", features = ["dir_source"] }
serde = "1.0"
serde_json = "1.0"
pnet = "0.28.0"
pnet_datalink = "0.28.0"
dotenv_codegen = "0.15.0"
dotenv = "0.15.0"
listenfd = "0.3.3"
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"]}
anyhow = "1.0"
chrono = "0.4.15"
