[package]
name = "tide-server"
version = "0.1.0"
authors = ["gary"]
edition = "2018"

[dependencies]
pnet = "0.28.0"
pnet_datalink = "0.28.0"
tide = "0.16.0"
async-std = { version = "1.8.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
