[package]
name = "tower-server"
version = "0.1.0"
authors = ["gsuyemoto <gsuyemoto@gmail.com>"]
edition = "2018"

[dependencies]
tower-web = "0.3.7"
pnet = "0.28.0"
serde = "1.0.126"
log = "0.4.0"
env_logger = "0.8.3"
